services:
    oportunidade.repository:
        class: Infrastructure\Pesistence\Doctrine\OportunidadeRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Domain\Model\Oportunidade
